[package]
name = "p3rust"
version = "0.1.0"
authors = ["tomwatt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
serde_json = "1.0.57"